name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run unit tests
        run: ./test-unit.sh

      - name: Install screen
        run: sudo apt-get install -y screen

      - name: Run system tests
        run: ./test-system.sh
